### ISSUE TITLE
All Ship's Sound Effects disappear with this mod installed on 1.12.1 (Engine sound effects and all other parts)

### ISSUE THREAD

**Issue by Alexsys** [zer0Kerbal/Pteron#10]
Upon digging, I discovered that this mod in particular causes all sound effects of a ship to simply stop playing, it goes mute. Unless you restart and verify.

Don't have many mods, but I removed each and every, and got to the result of Pteron being the one causing it. 
A lovely mod alas, quickly became a favorite grand mod, but with this issue its a problem

Something in the Mod itself causes a corruption of sound effects for some reason. To think of it, I never actually heard the sounds of the Pteron engines, except from the RCS. I might be wrong, maybe that's the reason it removes the rest as well?

**To Reproduce**
Have the mod on,
 launch a ship (With Pteron Tinyship on it, in my case it was docked in ship from launch), play with it for some time, maybe even reload a quicksave, and suddenly no sound for the ship, requiring a restart of the game / verify.

Also I did not have this dependency mod Firespitter, it is causing several problems due to being outdated, so i didnt care much about the wheels, and did not have it on as of now.

**Expected behavior**
The sound effects will poof. 
The ship's engine sounds, and gear movement (legs retracting and extending) to be exact.

**Desktop (please complete the following information):**
 - OS: Win10, computer of the gods.
 - Version 1.12.1

**Comment by zer0Kerbal** [comment]
@Alexsys thank you for the issue. Puzzling, especially since there is only parts (.mu .dds .cfg) in this mod, and if you don't have firespitter installed...

which version of this mod did you have installed?

**Comment by zer0Kerbal** [comment]
I just loaded up 1.11.x with no firespitter and Pteron 0.9.0.0 installed.

- launched 
- edited into space.
-  quicksaved 
- named quicksaved.
- [x] made sure sound
- [x ] loaded quicksave
  - [x] made sure sound
- [x ] loaded named quicksave
  - [x] made sure sound

Don't think Pteron is the issue - heard RCS sounds / Engine sounds all three times.

Am open to more information.

**Comment by Alexsys** [comment]
> I just loaded up 1.11.x with no firespitter and Pteron 0.9.0.0 installed.
> 
> * launched
> * edited into space.
> * quicksaved
> * named quicksaved.
> * [x]  made sure sound
> * [x ] loaded quicksave
>   
>   * [x]  made sure sound
> * [x ] loaded named quicksave
>   
>   * [x]  made sure sound
> 
> Don't think Pteron is the issue - heard RCS sounds / Engine sounds all three times.
> 
> Am open to more information.

Hello,

The version is 1.12.1, the game and the mod itself. Didn't use it on 1.11

**Comment by Alexsys** [comment]
Aight, I managed to dig in and find out that some other unknown script for now is causing this thing, 
not the Pteron mod, which coincidentally made the issue to occur less, but wasnt the origin.
I'll close this one, and try to figure this one out.

great mod though, the tiny ship is of many uses in ksp, glad its not the cause.
