### ISSUE TITLE
Pteron's Docking Collar does not dock while attached to Pteron itself, only when it ''undocks itself'' from the minishuttle

### ISSUE THREAD

**Issue by Alexsys** [zer0Kerbal/Pteron#13]
Surprisingly, I've had this issue for quite a long while that when the Docking collar itself is attached to the Pteron, it lacks the function of a docking collar. Which means it does not attract magnetically to any other port, nor it attaches.
It acts like just some random part that isnt meant to dock
UNTIL
You right click on the docking collar, and press Undock, which detaches itself from the pteron, and surprisingly then magnetizes itself to the nearby docking port you've been trying to connect to immediately, and gets itself attached nicely like a regular docking port.

Sadly it seems to refuse to act like a docking port while attached to the Pteron itself, and when disconnected it suddenly regains its docking port properties and function.

To reproduce simply attach that docking collar to the back of the pteron and try to dock to any other port.

**Comment by zer0Kerbal** [comment]
0.9.9.9-prerelease should fix this.
