### ISSUE TITLE
A very dear request that will improve this mod by 1000%

### ISSUE THREAD

**Issue by Alexsys** [zer0Kerbal/Pteron#21]
The mini shuttle is grand, but there is one issue that makes it worse than grand, and its the landing gear.
It has a terrible invisible ghost hitbox that is very sensitive and badly placed, causing take offs and landings to be broken and explosive 99% of the times, creative workarounds don't work

Firestorm mod sadly is VERY junky on modern KSP and damages many mods without fix, it can be concluded that firestorm is one of those mods that if you install you gotta pass on way too many good modern others, making firestorm obsolete. 
Also maybe its even incompatible with 1.12? unsure.

So the issue,
The model hitbox or frame includes in itself those invisible wheels even if not deployed, and that is the massive destroyer explained why below:

If there would be an option to have the Pteron wings **detached** in the editor, from their current state which are Wings including gears in them, that would be amazing.

This picture displays why
https://i.imgur.com/0BXSaWf.jpeg

It means nothing if they're in or out, its just a decoration apparently, if you simply use stock game and pteron at least.
https://i.imgur.com/HXz9FGE.jpeg

Employing all the powers of Tweakscale to try and make wheels that overshadow the invisible explosive hitbox still doesn't eliminate the fact that it forces explosions evrey single time the wheels take stress (from the weight of the craft), forcing them to go up n down, thus the invisible STATIC hitbox gets touched and blows up.

https://i.imgur.com/40WWyp5.jpeg
(this still blows up, and this is my finest attempt yet after so many tries ever)

So sadly in its current state, other than a space drone and a glider with parachutes to return to kerbin, the craft's purpose is stripped from it by a large portion,
you either gotta give up the wings or give up making it land or take off from atmosphere ground.

pteron is unlandable on kerbin, and un take offable.

valve please fix

**Comment by zer0Kerbal** [comment]
@Alexsys thank you.
- I've landed it numerous times. It is landable. 
- Any modeling issues are beyond my ability. 
- Firespitter is unusable, and both issues and a PR have been sitting with the repo for quite some time. It is the reason I just made them an animation.  With @lisias's version of Firespitter - they work, but the vessel spawns 1000m above the launchpad/runway.
- It is meant to launch as the shuttle did - as a rocket. hence skids.
- will see what else can be done upon the next pass.
