### ISSUE TITLE
''Stowed'' drag on both Pteron parachutes is too big, needs tweaking

### ISSUE THREAD

**Issue by Alexsys** [zer0Kerbal/Pteron#22]
https://i.imgur.com/G5GmRia.jpeg
(2 mini pteron Drought chutes and 2 mini pteron normal chutes)

Couldn't understand why my Pteron was pitching down in atmosphere 24/7,
All the correct parameters were alligned, TWR was messed with billion of times,

apparently its the drag the Pteron parachutes create, I do not know whether if it is because they got a default stowed drag parameter and since the pteron is tiny it creates more drag since its technically the draggiest item on the shuttle, 
(in screenshot you can see that the only other draggy dragger is the radial air intake, and even that is not THAT much)

so I removed them from my pteron, and suddenly the shuttle is barely pitching down and is able to fly straight.

The drag probably needs to be toned down massively, and maybe making them lighter as well. since they cant be Tweakscaled, so its unabuseable considering that if they're tweaked for lower mass crafts like pteron, it'll work well.

**Additional feedback note on Pteron in general**
I think some other things need tweaking, since flying the pteron in Atmosphere is a hard and problematic task.
Even if you overcome over the shadow wheels that cause crashing into the ground, you'll find the narrowness of the shuttle being horrible for landing, so you need to do a very very soft landing since its so easy to be flipped, especially when you suddenly break.
(I cant imagine the original Firestorm wheels being ANY effective in landing, theres no way they'd land smoothly and not flip the plane with being so narrow. So even with the widest possible wheel placement, its still suicidal to land this shuttle like a normal plane.)

It needs some tweaking to actually feel like a shuttle, it feels like the Pteron isnt packaged ready, its like a model you gotta tweak yourself, not really a slap on the parts and fly, and is very underpowered in atmosphere conditions since its shape and size is just not proportionate by KSP physics apparently. Terrible atmosphere engines too, without the ability to tweakscale they're too weak to carry the bird in the earth sky.
Since engines are weak in atmosphere so you gotta think outside the box to make it work, but then the wheels and its ratio is too narrow so you gotta tweakscale some wheels that dont spasm, but then you cant brake since the plane flips to the side when you hit the brakes.

Difficult yet pretty plane

**Comment by zer0Kerbal** [comment]
@Alexsys thank you.
- this is due for an update pass - to finally release it from pre-release
- both engines should be multi-mode - one VAC one with pretend 'afterburners' so to speak (atmos mode)
-  love the suggestions - now if they could be made solid.

**Comment by Alexsys** [comment]
> @Alexsys thank you.
> 
> * this is due for an update pass - to finally release it from pre-release
> * both engines should be multi-mode - one VAC one with pretend 'afterburners' so to speak (atmos mode)
> * love the suggestions - now if they could be made solid.

Ah legendary. a new pre release is incoming? thats awesome

**Comment by zer0Kerbal** [comment]
> Ah legendary. a new pre release is incoming? thats awesome

yes, 

in fact _if I am remembering correctly_ Pteron is up next after SimpleConstruction! (which should be done this weekend)

**Comment by zer0Kerbal** [comment]
I have (*knocking on wood*) figured out the missing FX on the engines - so am working on this as I type.

I will also update the readme.me to indicate this is **not** a ssto - rather it is a like the space shuttle - launches vertically, lands horizontally.

**Comment by zer0Kerbal** [comment]
Also both engines are multimode - one `VAC` and one `Afterburner` (aka atmospheric)

**Comment by zer0Kerbal** [comment]
finally - the command module has a up and down mode - (I know the up - which is pitch up 15°) - which I try to put on all my shuttles.

**Comment by Alexsys** [comment]
Certainly hope you're gonna give yourself a splendid new year's break rest, thats a massive collection of progress I see bombarded.

**Comment by zer0Kerbal** [comment]
the 'chutes' should be not so much of a stowed drag... still having issues with engineFX
